# Generated by Django 5.0.4 on 2024-05-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='ltc',
            field=models.CharField(default='0.00000000/0.00000000', max_length=100, verbose_name='LTC (Cleared/Uncleared)'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='btc',
            field=models.CharField(default='0.00000000/0.00000000', max_length=100, verbose_name='BTC (Cleared/Uncleared)'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='eth',
            field=models.CharField(default='0.00000000/0.00000000', max_length=100, verbose_name='ETH (Cleared/Uncleared)'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='xmr',
            field=models.CharField(default='0.00000000/0.00000000', max_length=100, verbose_name='XMR (Cleared/Uncleared)'),
        ),
    ]
