# Generated by Django 5.0.4 on 2024-05-05 21:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_wallet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txnid', models.CharField(max_length=100, verbose_name='Txn ID')),
                ('txnhash', models.CharField(max_length=100, verbose_name='Txn Hash')),
                ('token', models.CharField(max_length=100, verbose_name='Token')),
                ('amount', models.CharField(max_length=100, verbose_name='Amount')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('date', models.DateField(default=datetime.datetime(2024, 5, 6, 3, 23, 52, 338627), verbose_name='Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
