# Generated by Django 5.0.4 on 2024-05-06 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 23, 22, 56, 230473), verbose_name='Date'),
        ),
    ]
